(when (maybe-require-package 'helm)
  ;; to fix this bug in emacs-26
  (when (version< emacs-version "27.0")
	(setq x-wait-for-event-timeout nil))
  (helm-mode 1)
  ;; setting the hotkeys
  (global-set-key (kbd "M-x") #'helm-M-x)
  (global-set-key (kbd "C-x b") #'helm-mini)
  (global-set-key (kbd "C-x r b") #'helm-filtered-bookmarks)
  (global-set-key (kbd "C-x C-f") #'helm-find-files)
  (helm-projectile-on)
  (after-load 'projectile
	(define-key projectile-mode-map [remap projectile-ag] #'helm-projectile-ag)
	(define-key projectile-mode-map [remap projectile-switch-project] #'helm-projectile)
	(define-key projectile-mode-map [remap projectile-find-file] #'helm-projectile-find-file))
  (global-set-key (kbd "C-c s s") #'helm-ag)
  )
(maybe-require-package 'helm-projectile)
(maybe-require-package 'helm-ag)
(provide 'init-helm)
