(when (maybe-require-package 'go-mode)
  (setq gofmt-command "goimports")
  (add-hook 'go-mode-hook (lambda()
				(when (maybe-require-package 'company-go)
				  (set (make-local-variable 'company-backends) '(company-go))
				  (setq company-go-show-annotation t)
				  )
				(add-hook 'before-save-hook 'gofmt-before-save)
				(flycheck-mode)
				(when (maybe-require-package 'go-eldoc)
				  (go-eldoc-setup))
				(define-key go-mode-map (kbd "M-.") 'godef-jump)
				(add-to-list 'flycheck-disabled-checkers 'go-test)
				(add-to-list 'flycheck-disabled-checkers 'go-unconvert)
				(add-to-list 'flycheck-disabled-checkers 'go-errcheck)
				(add-to-list 'flycheck-disabled-checkers 'go-vet)
				(add-to-list 'flycheck-disabled-checkers 'go-gofmt)
				(add-to-list 'flycheck-disabled-checkers 'go-golint))))
(provide 'init-go)
