#! /bin/sh

## some setting
xrandr --output DP1 --right-of HDMI2
feh --bg-scale ~/pictures/simple.png

# bspwm configuration
bspc monitor HDMI2 -d   
bspc monitor DP1 -d    
bspc config border_width         2
bspc config window_gap          12
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
bspc config pointer_follows_monitor true

# star application
sxhkd  > /dev/null 2>&1 &
fcitx > /dev/null 2>&1 &
compton > /dev/null 2>&1 &
polybar DP1> /dev/null 2>&1 &
polybar HDMI2> /dev/null 2>&1 &
