#! /bin/sh
bspc config border_width         2
bspc config window_gap          12
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
bspc config pointer_follows_monitor true
bspc rule -a Emacs state=tiled
# sxhkd which is a simple X hotkey daemon
sxhkd > /dev/null 2>&1 &
# fix cursor displays X when not over window 
xsetroot -cursor_name left_ptr > /dev/null 2>&1 &
HOST=`hostname`
if [ "$HOST" = "lazzy-company-pc" ];then
    bspc monitor HDMI2 -d   
    bspc monitor DP1 -d    
    polybar DP1   > /dev/null 2>&1 &
    polybar HDMI2 > /dev/null 2>&1 &
fi

if [ "$HOST" = "lazzy-home-pc" ]; then
    bspc monitor DP-0 -d       
    polybar DP-0 > /dev/null 2>&1 &
fi


